### ISSUE TITLE
Rename files if the characters are not supported on the receiving operating system

### ISSUE THREAD

**Issue by alexmozaidze** [localsend/localsend#1063]
### Describe the bug

When trying to send a file with characters permitted on sender's OS, but illegal on receiver's OS, it errors with:
- Sender: `[500] Could not save file`
- Receiver: `PathAccessException: Cannot open file, path = '/bla/bla/my:cool:video.mp4' (OS Error: Operation not permitted, errno = 1)`

The error does not occur if `my:cool:video.mp4` is renamed to `my_cool_video.mp4`.

### To reproduce

1. Create a file with some funky characters that are illegal on the receiver's OS

```
my:cool:file.txt
```

2. Send this file to the receiver
3. Gaze upon the error messages on both devices

### Expected behavior

It should probably replace illegal characters with underscores, since most operating systems allow them in filenames. It would also be nice if the user was notified beforehand when the file will be renamed on the receiver's end.

### Desktop (please complete the following information)

- OS: Void Linux (ext4 filesystem)
- LocalSend Version: 1.13.1

> [!NOTE]\
> LocalSend was installed and ran using flatpak.

### Smartphone (please complete the following information)

- Device: Xiaomi Redmi 10C
- OS: Android 13
- LocalSend version: 1.13.1

**Comment by Caesarovich** [comment]
I've made a PoC using the [`sanitize_filename`](https://pub.dev/packages/sanitize_filename) package and it fixes the issue. 
But before making a PR I would like to discuss further on the implementation. I have two main concerns:

1. The `sanitize_filename` library doesn't allow for granular sanitization. Which means that a filename that could be valid on a receiving Linux device, would still have the "Windows illegal characters" stripped from the filename. 
One might justify it as a *feature* because "This file's name is now properly named/It shouldn't have such characters anyway". But if we do decide that illegal characters should only be stripped if illegal on the target device, then I think it would be pretty easy to create a more granular version of `sanitize_filename`. 

2. The current UI (receive_tab) only displays the original filename. It would need to be updated to show the actual filename saved to the device. Or better there could be an indication that it is different from the original filename.


-> This issue is also related to this one #1180

**Comment by Tienisto** [comment]
Thank you @Caesarovich .
Since you can change the file name as a recipient already, we can reuse this feature to change it beforehand.
I think that your library is already quite good. A flag that the recipient is a Windows device is better but not important

**Comment by Caesarovich** [comment]
Hi, so I've made a Dart library called [legalize](https://pub.dev/packages/legalize). If @Tienisto agrees to using it, I'll make a PR during the week. I let you the care to review its source code, I'd be happy to have feedbacks as it is my first Dart lib.

**Comment by Caesarovich** [comment]
Hello again, I found some time to work on this. Here you can see a PoC:

https://github.com/localsend/localsend/assets/38408878/0ff318b2-37bf-4a12-83b5-36f015d1e0f2

It's on the renaming file part. I've added a check for invalid file names that prevent from confirming and shows a snackbar message. Otherwise if the user accepts incoming files without renaming them, the filenames are automatically sanitized before saving.

For the first part, I am not quite satisfied with Snackbar message. I wonder if I should instead write the warning message right under the input field. Like in this example:

![image](https://github.com/localsend/localsend/assets/38408878/03cc49a2-028a-4efc-a7b0-675c73dc34e2)

Implementation wise, I've just created a private validation method that is called before the submit method.

```dart
bool _validate(String input) {
    if (_textController.text.isEmpty) {
      context.showSnackBar("You must enter a file name.");
      return false;
    }

    if (!isValidFilename(input)) {
      context.showSnackBar("Invalid file name.");
      return false;
    }

    return true;
  }

  void _submit() {
    if (mounted) {
      String input = _textController.text.trim();
      if (!_validate(_textController.text)) {
        return;
      }
      if (!input.contains('.') && widget.originalName.contains('.')) {
        // user forgot extension, we fix it
        input = input.withExtension(widget.originalName.extension);
      }
      context.pop(input);
    }
  }
```

I'm really not proficient in Dart and Flutter so please let me know if this is not optimal. I know we could use a Form widget with the validator method, but I don't know if it has any benefits to validate a single input field.

**Comment by Tienisto** [comment]
Thank you @Caesarovich 
Your solution seems alright to me. A message beneath the text field would be better, but I can do this for you if don't mind

**Comment by Caesarovich** [comment]
Thanks for the comments @Tienisto. Below two other screencap with the error message directly below the field:

https://github.com/localsend/localsend/assets/38408878/6cfb2582-7ebd-4ec0-828b-eb0f0a2a1f04

https://github.com/localsend/localsend/assets/38408878/e3b2f6a9-ac0e-40a8-b2e8-e5123c1e4bce

There's one for the single file editing and one for the multi-file quick actions. If that's good to you I'll open a PR soon. I first to to clean the code a bit and include i18n support.
