### ISSUE TITLE
iOS can't find Windows though Windows can find iOS and transmit.

### ISSUE THREAD

**Issue by jjgt008** [localsend/localsend#1156]
### Describe the bug

iOS can't find Windows though Windows can find iOS and transmit.

### To reproduce

Just install the software. Basic function.

### Expected behavior

Issue continue bothering me after I tried:
1. Close the firewall on Windows entirely;
2. Use troubleshoot;
3. Give Localsend all ports access;
4. Setting other pairs of ports for two devices;
5. Reinstall the software;
and the problem remains the same. My router works just fine.
I can only use browser to receive files from iOS.

### Screenshots

<img width="673" alt="1Untitled" src="https://github.com/localsend/localsend/assets/67328361/a17c1380-36b2-4d24-9544-657c9c173d04">

### Desktop (please complete the following information)

Windows 11 22H2 Build 42

### Smartphone (please complete the following information)

iOS 17.3.1 Build 43

### Additional context

Wired.

**Comment by jjgt008** [comment]
Portable bug, don’t t use portable edition.

**Comment by AyanC1** [comment]
Can confirm this bug currently happening as well. My Android to Windows both discovers each other fine. My Android to  iPhone 14(running 17.4.1) again fine but my iPhone 14 to windows is where the issue lies.i can see my iphone in nearby devices from my windows machine but iphone doesn't show my windows laptop. New to ios if you can guide me on how to take logs will be more than happy to help

**Comment by jjgt008** [comment]
> Can confirm this bug currently happening as well. My Android to Windows both discovers each other fine. My Android to iPhone 14(running 17.4.1) again fine but my iPhone 14 to windows is where the issue lies.i can see my iphone in nearby devices from my windows machine but iphone doesn't show my windows laptop. New to ios if you can guide me on how to take logs will be more than happy to help

just don‘t use portable version on windows

**Comment by AyanC1** [comment]
>
> just don‘t use portable version on windows

I am not. It's an installed version. But will reinstall it

**Comment by ghost** [comment]
A year later, I have the same issue. I see my iPhone on Windows but not the other way around.

**Comment by YIKIKRULES** [comment]
same here

**Comment by wayne931121** [comment]
I set the rule 53317 port tcp can enter firewall, then I can find my windows.

**Comment by remvn** [comment]
For me it was local network permission on IOS, try to enable it in Settings > Privacy & Security > Local Network. Also make sure to set firewall rule for Windows too.

**Comment by Sahir-110** [comment]
Mostly the problem is not with personal computing devices(Phone, tablets, laptop), it is with the ICT - Information Communicational Technology Device (Router). **Check this setting** Go to your router: 
1. 192.168.0.1
2. Wireless - Wireless Advanced. Find " Enable Client Isolation" and uncheck it. 
3. Save and go to your Localsend now.
