### ISSUE TITLE
Question: The new app version 1.14.0, is still unavailable both on Google Play and F-Droid

### ISSUE THREAD

**Issue by sergd88** [localsend/localsend#1181]
### Is your feature request related to a problem? Please describe.

This question is rather for the author of the app. I'd like to inquire why version 1.14.0 is still unavailable on Google Play? And strangely enough, in F-Droid as well. I understand that platform moderation doesn't always happen quickly, but a delay on both Android platforms for approximately 5 days seems a bit strange. However, it should be noted that the new version is indeed available on the Amazon Appstore. In general, I'd appreciate a response.

### Describe the solution you'd like

None.

**Comment by Tienisto** [comment]
On F-Droid, there was an issue that it couldn't be built on their servers. It is solved now and the update should be available in a few days.

On Google Play Store, they rejected the update due to the `MANAGE_EXTERNAL_STORAGE` permission (although it already existed in 1.9.0 a year ago).
This permission grants LocalSend direct access to the file system which is needed to select folders including their sub folders.

I am currently in contact with Google to discuss this issue.

**Comment by sergd88** [comment]
> On F-Droid, there was an issue that it couldn't be built on their servers. It is solved now and the update should be available in a few days.
> 
> On Google Play Store, they rejected the update due to the `MANAGE_EXTERNAL_STORAGE` permission (although it already existed in 1.9.0 a year ago). This permission grants LocalSend direct access to the file system which is needed to select folders including their sub folders.
> 
> I am currently in contact with Google to discuss this issue.

Clearly. Thanks for your response.

**Comment by sergd88** [comment]
> On F-Droid, there was an issue that it couldn't be built on their servers. It is solved now and the update should be available in a few days.
> 
> On Google Play Store, they rejected the update due to the `MANAGE_EXTERNAL_STORAGE` permission (although it already existed in 1.9.0 a year ago). This permission grants LocalSend direct access to the file system which is needed to select folders including their sub folders.
> 
> I am currently in contact with Google to discuss this issue.

Clearly. Thanks for your response.
