### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kevinsnameneedlong** [localsend/localsend#1263]
### Is your feature request related to a problem? Please describe.

This project would be the best if online collaboration features were added. Think about it?

### Describe the solution you'd like

Whether it can be achieved by means of plug-ins?

### Additional context

Partners in the LAN can work together on documents, which will greatly facilitate daily work and life. That's cool!

**Comment by Mennaruuk** [comment]
Interesting request. Is this even possible? Providing a connection to exchange files or Unicode text is one thing. Providing a multifaceted and complex connection between two programs running on different devices so that users could edit documents or annotate images simultaneously is very, very different. I don't even think office suites like Microsoft Office and LibreOffice support collaborative realtime editing. You might cite Collabora, but how it works is that it keeps the same file on its server then updates it whenever it changes. CryptPad solves this problem with encryption, but the key point here is that CryptPad is a collaboration suit, not a file-sharing service.

I think you're asking for a protocol that can make collaborative realtime work happen across any app, roughly similar to something like ActivityPub. Not only would such a protocol need to be made, but developers would actually have to adopt it, and I doubt that would happen anytime soon.

**Comment by Caesarovich** [comment]
As @Mennaruuk explained, this is beyond the scope of LocalSend. 

> @Tienisto I think we can close this as "unplanned" or something.
