### ISSUE TITLE
Remove MSIX and only provide EXE installer

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#1464]
An app installed with MSIX has a dynamic path based on the version of the app. This makes it difficult to have a common autostart implementation resulting in an unstable autostart experience (see: #464, #1231, #1293, #687).

To fix this, I propose to remove the MSIX installer altogether and to solely focus on the EXE installer (via InnoSetup) and the portable version. This simplifies the autostart implementation by only updating the Windows registry (here we can reference the executable because we can assume that the path never changes).

The problem I see is that Winget currently uses MSIX. I don't know if a migration is possible or if users are forced to uninstall the app. @sitiom @brogers5

**Comment by brogers5** [comment]
As far as Windows is concerned, the resulting installations from both the MSIX and EXE installer packages are treated as separate applications, so a direct replacement wouldn't be possible. They theoretically could live side-by-side with each other, but to avoid user confusion and other possible issues, I would lean toward implementing a one-time `Task` in Inno Setup to uninstall the MSIX installation if it exists. Worst case scenario, I can confirm this would be implementable in the Chocolatey package.

LocalSend's configuration appears to carry over seamlessly between the two installations, so I think we're good to go there.

As far as the Chocolatey package is concerned, based on some recent testing, I think we'll be fine as long as the Chocolatey package's version number changes as per usual. I actually looked into supporting the EXE installer earlier when it first dropped, but ultimately scrapped the idea after running into a nasty bug with Chocolatey's [Automatic Sync feature](https://docs.chocolatey.org/en-us/features/package-synchronization/automatic-sync/). Turns out that depends on Chocolatey's ability to take a snapshot of file and registry changes during the package's install/upgrade process, which caused problems when switching between consuming the EXE and MSIX installer. If only one installer type will exist going forward, this shouldn't be an issue.

All that being said, I'd be hesitant to assume the installation path will never change. You may recall v1.12.0 pointed a default All Users installation toward the 32-bit Program Files directory (#830), and the fix for that redirected it to the 64-bit directory. Regardless, users still have the option to redirect the installation elsewhere when upgrading via [Inno Setup's `/DIR` parameter](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline), even if the option is normally not presented during a non-silent upgrade. You may want to consider conditionally updating the autorun registry value with the finalized install location post-install.
