### ISSUE TITLE
Android: Migrate away from MANAGE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#1493]
Google rejected any update from v1.14.0 onwards because `MANAGE_EXTERNAL_STORAGE` is used.

I do agree that LocalSend can use less permission to operate, however, Android 11 requires [scoped storage](https://developer.android.com/about/versions/11/privacy/storage) which Flutter doesn't fully support (https://github.com/flutter/flutter/issues/147037). (very funny because Flutter and Android are both developed by Google)

This permission was added in this commit 8ebec6f2, so that arbitrary folders can be created and read.

**Comment by sudoshindo** [comment]
Can't set save folder to `Download` anymore? (`/storage/emulated/0/Download`)

**Comment by Tienisto** [comment]
I cannot reproduce this @sudoshindo 
It somehow works on my Samsung phone and also in the Android emulators.

**Comment by sudoshindo** [comment]
@Tienisto sorry, I should have been more clear about what I said.

I don't have a bug or issue with the apps.

I'm just asking if this permission you removed will stop users from picking `/storage/emulated/0/Download` as the Save Folder. 

A lot of apps can't use Download directly anymore because Android/Google doesn't allow it. You have to make a subfolder under Download, like `Download/Localsend`.

**Comment by Tienisto** [comment]
Thanks for your input. I've noticed that you don't have read access to the Download folder but you can write anything. So if you keep the default setting, then everything should work as before.
