### ISSUE TITLE
v1.16.1 version of localsend disappears when Command key is clicked on macOS 15.1

### ISSUE THREAD

**Issue by temporalu** [localsend/localsend#2037]
### Describe the bug

You open the app, you hit the Command, the window disappears. This bug prevents from using cmd+c and cmd+v and alike keyboard shortcuts to function normally.

### To reproduce

1. Open the app
2. Click Command key
3. Window disappears

### Expected behavior

1. Open the app
2. Click Command key
3. Nothing happens

### Screenshots

![CleanShot 2024-11-13 at 10 57 56](https://github.com/user-attachments/assets/6441a0aa-d415-4331-baeb-bdd82c25536b)

### Desktop (please complete the following information)

- macOS 15.1

**Comment by imeursault** [comment]
I encountered same problem, macOS 15.1 and LocalSend version 1.16.1(56).
When the cmd key is pressed, the program exit.

**Comment by closure11** [comment]
@Tienisto I found the perfect way to reproduce this issue:
 
1. Turn on the "Minimize to the System Tray/Menu Bar when closing" setting.
2. Close LocalSend using Command + W.
3. Reopen LocalSend, and then, as soon as the Command key is pressed, the app will automatically minimize.

If LocalSend is closed by clicking the close button with the mouse in step 2 instead of using the keyboard shortcut, the issue cannot be triggered.

**Comment by Tienisto** [comment]
Thanks for your reproduction steps @closure11 !
This seems like a bug in the Flutter engine. However, I've found a workaround so this should be fixed now.
