### ISSUE TITLE
LocalSend stuck at sending files but succesfully sent the files

### ISSUE THREAD

**Issue by Linkachus17** [localsend/localsend#259]
### Describe the bug

Maybe because the file is too big (like 100MB+), the App (both PC and mobile side) stuck at sending screen, but once it reach Total Progress 0:00 I can still see the file have been transferred successfully to the mobile from Files app

### To reproduce

1. Open LocalSend both PC and mobile
2. Start sending files, maybe try bigger files like 100MB because in my case it's 93MB
3. Wait until the transfer is finished
4. See the screenshot

### Expected behavior

Expecting Finished Successfully screen

### Screenshots

![image](https://user-images.githubusercontent.com/50126684/223994732-d6b170b0-28c0-432d-b6c1-dc225a71fc34.png)

### Desktop (please complete the following information)

OS: Windows 11 
Version: 22H2
Build: 22621.1105

### Smartphone (please complete the following information)

Device: iPhone XS
OS: iOS 16.3

**Comment by NolanNolan** [comment]
uninstalled. i have the same problem - its so cumbersome that very few apps actually work.

**Comment by Linkachus17** [comment]
> uninstalled. i have the same problem - its so cumbersome that very few apps actually work.

App works just fine for me since then

**Comment by NolanNolan** [comment]
Hi

Ok since when  - i.e., what do you mean ?

Hilsen Jørn

Fra: Linkachus17 ***@***.***>
Sendt: 27. november 2024 19:38
Til: localsend/localsend ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Comment ***@***.***>
Emne: Re: [localsend/localsend] LocalSend stuck at sending files but succesfully sent the files (Issue #259)


uninstalled. i have the same problem - its so cumbersome that very few apps actually work.

App works just fine for me since then

**Comment by NolanNolan** [comment]
ok, but since when - ie what do you mean ?

**Comment by Linkachus17** [comment]
> ok, but since when - ie what do you mean ?

Long time ago, maybe like 2 days after making this issue

**Comment by NolanNolan** [comment]
So how can this be solved ?

I just installed the versins today and had this issue

**Comment by NolanNolan** [comment]
So how can this be solved ?

I just installed the versins today and had this issue

Hilsen Jørn

Fra: Linkachus17 ***@***.***>
Sendt: 27. november 2024 19:42
Til: localsend/localsend ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Comment ***@***.***>
Emne: Re: [localsend/localsend] LocalSend stuck at sending files but succesfully sent the files (Issue #259)


ok, but since when - ie what do you mean ?

Long time ago, maybe like 2 days after making this issue

**Comment by Linkachus17** [comment]
> So how can this be solved ?
> 
> I just installed the versins today and had this issue

No idea, it solved itself...I think? because this is long time ago and I am on totally different system now (Arch Linux), and I have never had any issues ever since

**Comment by NolanNolan** [comment]
OK seems setting timeout to 1000 solved it

Thanks

Nolan
