### ISSUE TITLE
UI Glitches on Ubuntu / Linux

### ISSUE THREAD

**Issue by 1023386568** [localsend/localsend#337]
### Describe the bug

When open the application on Ubuntu, the GUI will be wrong

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

GUI can be normally

### Screenshots

![截图 2023-03-27 13-38-47](https://user-images.githubusercontent.com/79915693/227851015-0f0aa5ea-125a-46a9-bed2-c390561dde1f.png)

**Comment by Tienisto** [comment]
This is most likely a bug from the Flutter engine.

**Comment by TheGB0077** [comment]
This glitch happens because the set_default_size (500x400) for the GTK_HEADER_BAR doesn't match the application size of 900x600, although not setting the default size makes the glitch worst.
No problems at all if the Header bar is disabled.

https://github.com/localsend/localsend/blame/47012406306ee72b98b41520e6541fb5a630ff59/linux/my_application.cc#LL50

**Comment by Tienisto** [comment]
@TheGB0077 maybe this this https://github.com/localsend/localsend/commit/273b59e4c25c8a72816253a23c7c658b9282f91f commit fixes the problem
