### ISSUE TITLE
Flatpak 1.9.0 release

### ISSUE THREAD

**Issue by Tienisto** [localsend/localsend#413]
Due to a dependency issue of [libayatana-appindicator](https://github.com/AyatanaIndicators/libayatana-appindicator), version `1.9.0` cannot be released.

Ref: https://github.com/flathub/org.localsend.localsend_app/pull/6

**Comment by tesfabpel** [comment]
Wouldn't it be better to optionally depend on the library such that if it's there the tray icon is used, otherwise it isn't?
Given 1.9.0 new features, I'd prefer having an up-to-date app without the tray icon (since it has only the show and exit options) than having a stale app while fixing the dependency issue.
Sadly, I'm not a flutter dev so I can't help too much...
Anyway, thank you!

**Comment by Tienisto** [comment]
The flatpak version works now.
