### ISSUE TITLE
Feature request: Multi-select items on iOS

### ISSUE THREAD

**Issue by nbarari** [localsend/localsend#470]
### Is your feature request related to a problem? Please describe.

Currently when selecting items on iOS (ex: photos and files), the checkbox for each item just be individually tapped

### Describe the solution you'd like

Have an option to select multiple items at once. This can be achieved via hold and swipe in a direction or double finger hold and move in a direction

**Comment by kiiwii** [comment]
Approve & agree.  Will do a great convenience

**Comment by mak448a** [comment]
Please consider this feature. Many people have asked for it on the App Store reviews. Thank you @Tienisto

**Comment by Tienisto** [comment]
Closing this in favor of #376

**Comment by dasl-** [comment]
Bulk selection of photos on iOS can be achieved with the native Photos app ([demo](https://www.youtube.com/watch?v=xGebGApylWE&t=55s)].

1.  Once photos / videos are selected in the iOS Photos app, click the "share" icon in the bottom left corner: 

  <img src="https://github.com/user-attachments/assets/9bd06009-0a27-4679-b6ad-3bb3d73bab41" width="200"/>

2. Click the "Options >" button at the top

    <img src="https://github.com/user-attachments/assets/72607536-ed6a-4cec-b2be-d92d30ce8be2" width="200"/>

3. Select "Current". This ensures that the original file will be shared, rather than a transcoded version.

  <img src="https://github.com/user-attachments/assets/8cb3cc33-3f6e-40c4-8302-f4c8b6523981" width="200"/>

4. Back at the same screen from step 2, click the "More" button on the right side: 
  <img src="https://github.com/user-attachments/assets/72607536-ed6a-4cec-b2be-d92d30ce8be2" width="200"/>

5. Select LocalSend from the list of apps with which to share the photo/video:
  <img src="https://github.com/user-attachments/assets/c88ba9db-be66-4558-be7b-dcce3c95f1ae" width="200"/>

6. Done!


Unfortunately, I am not aware of a way to make "Current" the default in step 3.

See this issue for where I discovered this technique: https://github.com/localsend/localsend/issues/1830
