### ISSUE TITLE
LocalSend crashes or freezes when sending large files or folders

### ISSUE THREAD

**Issue by TeackReais** [localsend/localsend#489]
### Describe the bug

I used LocalSend to send a folder containing 15,000 images from my phone to my computer. The compressed size of the images was 9.68GB, and the folder size was 9.89GB. 
When I used LocalSend’s add folder option to send the entire folder, I selected the folder and then saw more than 15,000 files in the pending list. After clicking send, the app got stuck at waiting for the other party’s response (even though my computer had fast save enabled, which should skip this step). After a while, the app crashed. 
When I used LocalSend’s add file option to send the compressed file, I selected the file and then the app was spinning for 2-4 minutes. After that, it could send normally. If I used the built-in file sharing feature of my phone, and clicked on the LocalSend app, the app got stuck at a white loading screen for 1 minute and 50 seconds. After that, it could also send normally. 
These are the problems I encountered when using LocalSend to send large files and folders.

### To reproduce

send large files or folders

### Expected behavior

crashes or freezes

### Desktop (please complete the following information)

- OS macOS 13.4
- Version 1.9.1

### Smartphone (please complete the following information)

- Device Redmi K50
- OS Android 13 MIUI 14.0.6
- Version 1.9.1

**Comment by dhruvanbhalara** [comment]
I think it's due to saving files to the gallery taking time which causes the freezing of the main thread.

**Comment by KraXen72** [comment]
This also happened to me, with much smaller numbers:
1.55GB, 453 photos sending from phone (Samsung Galaxy M21, Android 12, OneUI 4.2) to pc (ASUS FX502VE windows 10, msix install of 1.11.1)
attempted twice, both times it showed a black screen in localsend for over a minute and then crashed. Happened both when using the share dialog from gallery, and when picking files from localsend android app

The most I've been able to successfully transfer (from my limited testing), was 186 files (693.5MB). This is most likely not the upper limit.
it is an annoyance, because i have to split the transferring to several batches.

**Comment by Tienisto** [comment]
Should be fixed in 1.15.2. Reopen if it still happens

**Comment by tmnrdhf** [comment]
@Tienisto I tried to send 1k phots from iOS to android (both on 1.15.3) and localsend wasn't even offered as an option in the iPhones send menu...

**Comment by DolanD2** [comment]
It still happens, I just tried to send 20k worth of images and videos (about 36gb) from my phone (Galaxy A52s) to a Windows 11 laptop and the app just crashed on the phone after sending a few files.

**Comment by uncharted-user** [comment]
I just experienced issue with 0.5 GB audio file and finally given up as there are no way to complete the transfer!

**Comment by xCaradhras** [comment]
Just happened to me with a 5.5 GB file, which I wanted to transfer from my Android Phone to a Windows 11 PC.
