### ISSUE TITLE
Did you buy GitHub stars?

### ISSUE THREAD

**Issue by bryantbiggs** [localsend/localsend#62]
https://www.reddit.com/r/github/comments/10ogfxj/i_got_18k_stars_after_bought_service_from_baddhi/

**Comment by Tienisto** [comment]
Nope, the "hype" was very natural in my opinion. You can checkout the amount of issues and pull requests in the recent days. I can also show you the download counts from Google Play and App Store if you want.

**Comment by bryantbiggs** [comment]
The fact this was closed so quickly without shock or response to said issue is highly suspect

<img width="777" alt="image" src="https://user-images.githubusercontent.com/10913471/215358608-1e30485d-8d34-4543-9610-c2b3c753ccd3.png">

**Comment by Tienisto** [comment]
I closed this issue so quickly because the "service" is so dumb that I feel personally attacked by your statement.

Why should someone buy Github stars? This repo is MIT licensed and anyone can copy this project and make it closed source / commercial. I don't care at all. I just wanted to have a file sharing solution because in 2023 every alternative is so clumsy to use.

**Comment by Tienisto** [comment]
I spent a lot of hard work into this project just be insulted by someone because some random Indian guy picked a trending github repo and say "Here my service worked, buy my github service it" LOL.

**Comment by Tienisto** [comment]
I understand the business model of this "service" a little bit if my repo was a library intended for other devs to use (Devs don't want a library nobody uses).

But LocalSend is a consumer app. Plain and simple. 99% of consumers don't care at all how many stars the "Github Repo" has. A fraction of users do care that it is FOSS, a fraction of a fraction care that it is published on F-Droid. But Github Stars? Wtf. This is like the worst way to spend money.

To be fair, I appreciate that my repo got a lot of likes recently. I only appreciate it because these likes are not fake. Even IF they are fake, then I couldn't care less. The contribution for human kind is determined by well engineered software not by the amount of likes!

So what's my finaly word? The Indian guy scammed you all - with a shady business model that does not make any sense - except for you.

**Comment by idjfia** [comment]
I shared LocalSend on Chinese website, maybe that's why the stars grow.

https://www.appinn.com/localsend/

https://meta.appinn.net/t/topic/39942

I'm sorry that this may have caused trouble to developer.

Excuse me that my English is poor.

**Comment by Tienisto** [comment]
No worries @idjfia .
The Chinese users opened a lot of issues and helped to improve this app a lot. Thanks!

**Comment by rollingmoai** [comment]
> I shared LocalSend on Chinese website, maybe that's why the stars grow.
> 
> [appinn.com/localsend](https://www.appinn.com/localsend/)
> 
> [meta.appinn.net/t/topic/39942](https://meta.appinn.net/t/topic/39942)
> 
> I'm so sorry that this may have caused troubles to developer.
> 
> Excuse me that my English is poor.

I can now say that by empirical evidence, Chinese users increase your star count by a tenfold. I've seen too many Chinese repos with way more stars than they should have 😅

Genuine question, I wonder why a month-old software shot up when a **very** similar app called [Sharik](https://github.com/marchellodev/sharik) (which I use and is also written in Flutter!) has already existed for a long time.
