### ISSUE TITLE
Feature request: Monochrome icon for the system tray

### ISSUE THREAD

**Issue by GaryElshaw** [localsend/localsend#649]
### Is your feature request related to a problem? Please describe.

This isn't a problem, but does make the sys-tray a little more harmonious for most users.

### Describe the solution you'd like

Implemented for the macOS client, i was wondering if it would be possible to have a monochrome icon for the linux system tray. LocalSend is currently the only anomaly for me.

![image](https://github.com/localsend/localsend/assets/69029666/2568a25e-1a5c-447c-befe-77dafae48a07)

I made some white versions of the icon if this helps at all.

[logo-white.zip](https://github.com/localsend/localsend/files/12474639/logo-white.zip)

**Comment by Tienisto** [comment]
Hello, for Linux, we use the [system_tray](https://pub.dev/packages/system_tray) package.

I also looked into the code of the specified package and it seems that the "isTemplate" parameter is only implemented for macOS. Notice that the icon is monochrome and changes to black and white depending on dark/light mode of macOS.

As this is not implemented on Linux yet, we have to speculate to either show the white or the black logo...
We can hope that someone implements a proper solution for Linux because I have only little knowledge about Linux desktop environments.

**Comment by GaryElshaw** [comment]
It looks great! Thank you @Tienisto 

![image](https://github.com/localsend/localsend/assets/69029666/41024240-0d30-4369-81d8-2b7097c6ef38)

**Comment by heddxh** [comment]
> The reason i say that is the thing with most linux desktop environments, is that the dark and light modes often only effect the ui of the application, but have no effect on the system tray, which is controlled elsewhere if using 'Tweaks'.

But that is what Gnome do but not on Kde: panel on Kde plasma will follow system color scheme so when use light scheme the icon is invisible.
It seems like the package system_tray don't have method to detect the color of panel, so should this issue reopen?

**Comment by GaryElshaw** [comment]
That sounds like a separate issue.

**Comment by Elaborendum** [comment]
I'm on Fedora Kinoite and the tray icon looks like this, using the 1.17.0 flatpak version, but my tray icon looks like this consistently, no monochrome icon version to be seen.

<img width="54" height="50" alt="Image" src="https://github.com/user-attachments/assets/a8722398-c560-4a4d-bac1-08e6259344b0" />
