### ISSUE TITLE
Alias follow device names

### ISSUE THREAD

**Issue by Jesse205** [localsend/localsend#685]
### Is your feature request related to a problem? Please describe.

Users need to view the alias of another device when facing multiple devices, which is inconvenient.

### Describe the solution you'd like

![Screenshot_20230915_062232_org localsend localsend_app](https://github.com/localsend/localsend/assets/51242302/241baa68-8311-4509-9cf6-4eac3a0a77ff)

I hope that the default alias will follow the device name. 

For example, my device name is HONOR 9X, alias defaults to HONOR 9X

![Screenshot_20230915_063100.jpg](https://github.com/localsend/localsend/assets/51242302/c2e2b3d5-dc3b-4deb-92ec-4c82e770d935)
![Screenshot_20230915_062756_org localsend localsend_app](https://github.com/localsend/localsend/assets/51242302/63d1a9a3-1a4e-4d68-a581-60f1cc315f3d)
![Screenshot_20230915_062758_org localsend localsend_app](https://github.com/localsend/localsend/assets/51242302/b35e5875-7640-42ba-9ed4-e322a808d18e)

**Comment by ImranR98** [comment]
It might be useful to use the "owner name" stored on the device as well, to get a more identifiable string.

**Comment by Caesarovich** [comment]
This is a feature I'd love as well. It would make it much easier for massive deployment scenarios. This way I don't have to make a script to edit the config files.

**Comment by Tienisto** [comment]
This is a trade-off between privacy and convenience. LocalSend just uses the behaviour similar to SnapDrop.

How do you deploy LocalSend in your "massive deployment scenarios"? @Caesarovich 

An option would be to show a setup screen on the first app start, so the user can choose between random and identifiable name.

**Comment by Caesarovich** [comment]
Hi @Tienisto , thanks for replying !

I understand the privacy concerns, but as LocalSend only works on LAN I don't believe "leaking" a device's name to be that much compromising (I'd be happy to hear any argument against that !). Things like NetBios already "leaks" a device's name on the LAN, and not even considering that Bluetooth "leaks" device names to other devices nearby that are not even from the same network. Again, I'm not familiar with LocalSend's protocol so maybe you have good concerns on that.

To clarify my use case, I manage a "huge" amount of devices across my company using **Ansible** scripts. In an ideal world, I'd just have to add LocalSend to my playbook, run the script and all of the computers then automatically install LocalSend through one of the supported package managers, and then no further configuration required on my part. Currently the first part works, but then I'll also have to walk up to each computers (hundreds of them....) to manually configure the LocalSend name.

I understand that LocalSend maybe wasn't designed for 'massive' deployment like this, and more oriented towards home network use, which it is perfect at and has been one of my favorite app in 2023 (Thanks for this awesome project). It's just that now I'd love to use it at work on scale (I showed it to some coworkers which loved it), and that I'm a lazy guy that loves automating even 10 seconds tasks :D .

That's why instead of making a script to edit the config files on my devices, I'd like to contribute that feature directly to localsend if anyone wants or if you agree with that. Of course we'd need to discuss how to properly implement it in a way that matches LocalSend's vision.

*Thanks for reading this long message.*

**Comment by Tienisto** [comment]
Closing this in favor of #977
