### ISSUE TITLE
Show favorite name instead of alias in the nearby device list

### ISSUE THREAD

**Issue by trymeouteh** [localsend/localsend#860]
### Is your feature request related to a problem? Please describe.

When you have several favorite devices saved, you will not know which device is which.

### Describe the solution you'd like

Please add a text field for favourite devices to label them. For example, if you want to saves your wife's device as a favorite you will set the name/label to "Wife's phone". This will help keep track of each favorite device and to know which one is which.

### Describe alternatives you've considered

None

**Comment by Tienisto** [comment]
You can actually edit the alias of your favorites. You need to open the favorite dialog by tapping on the "heart" icon

**Comment by trymeouteh** [comment]
The alias is the device name the other person has set, I want to suggest a name/label field that you can set to act as an way for you to know whose device is who.

Your wifes phone alias will be something like "Blueberry Rose". When you have several favorite devices saved, you do not know which one is your wife. By adding a label to them, you can distinguish which device is which.

The name/label is a separate field from the alias.

**Comment by Tienisto** [comment]
I see. The issue is that the name that you configure in the favorite dialog does not reflect in the device list

**Comment by sergd88** [comment]
Sounds great. Although I don't see the point in creating an additional field or label. We can currently edit the alias of the device added to Favorites, and that should be sufficient. Just need to display the name you set for the device, because the current implementation doesn't make any sense, since setting names has no effect on their display. Names in the list don't affect the display. It should be something like contacts, where you set a display name for the contact. This means a device can have one name set for display, but by adding it to Favorites, you could change its name to something else for your convenience. For instance, a device named Natalie by its owner could be renamed to Wife for your convenience through Favorites. And exactly the name Wife, when searching for the device or connecting, is what will be displayed for you.

**Comment by trymeouteh** [comment]
Would the IP and port number be considered the "device ID" which will distinguish a device in a local network?

Therefore the "Device Name" is now simply a label and in no way the actual unique ID for a device?

**Comment by Tienisto** [comment]
"Device Name" is just a label, you are right.
Each device using LocalSend has a random generated device id. This is used to check if the device is a favorite or not.

**Comment by trymeouteh** [comment]
> "Device Name" is just a label, you are right. Each device using LocalSend has a random generated device id. This is used to check if the device is a favorite or not.

Is this device ID visible to see?

**Comment by Tienisto** [comment]
Settings Tab -> About -> Debugging (scroll down) -> Security -> "Certificate SHA-256 (fingerprint)"

**Comment by trymeouteh** [comment]
> Settings Tab -> About -> Debugging (scroll down) -> Security -> "Certificate SHA-256 (fingerprint)"

Is this for iOS? There is not "About" option under the settings of the LocalSend app. There is also no "debugging" option on my android device in the Android Settings -> About section.

**Comment by trymeouteh** [comment]
Is this device id randomly generated when the app is first launched?

**Comment by Tienisto** [comment]
> Is this device id randomly generated when the app is first launched?

It is randomly generated on first app start

**Comment by trymeouteh** [comment]
Thank you for makIng this feature request and explaining how the device and and device id works
