### ISSUE TITLE
Feature request: Send to via LocalSend in the context menu

### ISSUE THREAD

**Issue by BenWBerger** [localsend/localsend#917]
### Is your feature request related to a problem? Please describe.

It would be great to have LocalSend in the context menu for Windows and probably macOS and Linux, for quick file transfer.

### Describe the solution you'd like

I described everything in the previous paragraph.

### Additional context

![202311191429](https://github.com/localsend/localsend/assets/151447702/c3770352-747a-441b-8006-2bb3aadfba99)

**Comment by sergd88** [comment]
While I personally don't use this feature, especially since it is not convenient at all due to the nested context menu in Windows, I have stopped using it on other platforms as well. However, I know many people who still use it. Therefore, I fully support the request for this feature, and it is entirely reasonable and logical, especially considering similar applications where such a feature is mostly present. However, the request for this feature has been mentioned multiple times before, for example, in [#499](https://github.com/localsend/localsend/issues/499), [#695](https://github.com/localsend/localsend/issues/695), [#115](https://github.com/localsend/localsend/issues/115), and even in #499, the author explained why he avoids implementing this feature. Therefore, most likely, the author will close this issue as a duplicate. Although in the same [#499](https://github.com/localsend/localsend/issues/499), user [Crazyroostereye1](https://github.com/localsend/localsend/issues/499#issuecomment-1616664089) suggests an implementation option for this feature that, at first glance, should not pose significant difficulties and should perform everything that users need.

**Comment by sergd88** [comment]
While I personally don't use this feature, especially since it is not convenient at all due to the nested context menu in Windows 11, I have stopped using it on other platforms as well. However, I know many people who still use it. Therefore, I fully support the request for this feature, and it is entirely reasonable and logical, especially considering similar applications where such a feature is mostly present. However, the request for this feature has been mentioned multiple times before, for example, in [#499](https://github.com/localsend/localsend/issues/499), [#695](https://github.com/localsend/localsend/issues/695), [#115](https://github.com/localsend/localsend/issues/115), and even in #499, the author explained why he avoids implementing this feature. Therefore, most likely, the author will close this issue as a duplicate. Although in the same [#499](https://github.com/localsend/localsend/issues/499), user [Crazyroostereye1](https://github.com/localsend/localsend/issues/499#issuecomment-1616664089) suggests an implementation option for this feature that, at first glance, should not pose significant difficulties and should perform everything that users need.

**Comment by Tienisto** [comment]
I see that there is high demand for context menus but my knowledge in Windows development isn't good enough to write native code. Flutter (the framework to build LocalSend) doesn't support this out of the box.

**Comment by Mark3xtrm** [comment]
> I see that there is high demand for context menus but my knowledge in Windows development isn't good enough to write native code. Flutter (the framework to build LocalSend) doesn't support this out of the box.

Is there any chance to see this as a Linux Mint Cinnamon Action?

**Comment by toyclyde** [comment]
I've added LocalSend to the Windows right-click SendTo menu with no issues.

You just need to copy the LocalSend shortcut to the following folder:

C:\Users\[Userename]\AppData\Roaming\Microsoft\Windows\SendTo

Change [Username] to your particular Windows username

GIF video:
https://i.imgur.com/BGIVUnI.gif
