### ISSUE TITLE
no chinese

### ISSUE THREAD

**Issue by luoxg** [localsend/localsend#965]
Why are there so many language options but no Chinese? Are you looking down on us China?

**Comment by sergd88** [comment]
> Why are there so many language options but no Chinese? Are you looking down on us China?

Understand, the author doesn't translate the entire program, he translates it only into English (which is considered the language of development) and into German, because he most likely uses it and knows it. All other languages are translated by community members, depending on who knows which language and who uses it. If there is no language in the application, it's only because there isn't a single person in the community who owns it or wants to use it and translate it. There is a whole "[Translation](https://github.com/localsend/localsend#translation)" section on the main page dedicated to this, where you can familiarize yourself with everything. There you can learn how to personally participate in the translation of the application into any language you wish.

P.S. As the author wrote, the application has a Chinese translation. It may not be complete, but again, if you wish, you can supplement it ourselves.

**Comment by Francesco146** [comment]
this issue should be closed as completed

**Comment by devcxl** [comment]
Yes, it's time to close it
